CREATE DATABASE ecommerce_de;

SHOW DATABASES;

CREATE TABLE ecommerce_transactions (
    Order_ID VARCHAR(20) PRIMARY KEY,
    Customer_ID VARCHAR(20),
    Order_Date DATE,
    Product_Category VARCHAR(50),
    Product_Name VARCHAR(100),
    Quantity INT,
    Unit_Price_USD DECIMAL(10,2),
    Discount_Percent DECIMAL(5,2),
    Payment_Method VARCHAR(50),
    Shipping_City VARCHAR(100),
    Country VARCHAR(100),
    Order_Status VARCHAR(30),
    Customer_Rating VARCHAR(20),
    Total_Amount DECIMAL(12,2)
);

select * from ecommerce_transactions;

-- Find the total number of orders.
SELECT COUNT(Order_ID) from ecommerce_transactions;

-- Find the total revenue (Total_Amount).
SELECT SUM(Total_Amount) FROM ecommerce_transactions;

-- Find the average order value.
SELECT AVG(Total_Amount) FROM ecommerce_transactions;

-- Find the highest order amount.
SELECT MAX(Total_Amount) FROM ecommerce_transactions;

-- Find the lowest order amount.
SELECT MIN(Total_Amount) FROM ecommerce_transactions;

-- Find the total revenue for each country.
SELECT Country, SUM(Total_Amount) 'Total_Revenue'
FROM ecommerce_transactions
GROUP BY Country;

-- Find the number of orders for each product category.
SELECT Product_Category,COUNT(Order_ID) 'Num_Of_Orders'
FROM ecommerce_transactions
GROUP BY Product_Category;

-- Find the average customer rating for each product category.
SELECT Product_Category,AVG(NULLIF(Customer_Rating,"Not Rated")) 'Avg_Rating'
FROM ecommerce_transactions
GROUP BY Product_Category;

-- Find the total quantity sold for each product category.
SELECT Product_Category,SUM(Quantity) 'Total_Quantity_Sold'
FROM ecommerce_transactions
GROUP BY Product_Category;

-- Find the revenue generated by each payment method.
SELECT Payment_Method,SUM(Total_Amount) 'Revenue_generated'
FROM ecommerce_transactions
GROUP BY Payment_Method;

-- Find the top 5 countries by total revenue.
SELECT Country, SUM(Total_Amount) AS "Total_Revenue"
FROM ecommerce_transactions
GROUP BY Country
ORDER BY Total_Revenue DESC
LIMIT 5;

-- Find the top 5 products by total revenue.
SELECT Product_Name, SUM(Total_Amount) AS "Total_Revenue"
FROM ecommerce_transactions
GROUP BY Product_Name
ORDER BY Total_Revenue DESC
LIMIT 5;

-- Find the product category with the highest average order value.
SELECT Product_Category, AVG(Total_Amount) AS "Avg_Order_Value"
FROM ecommerce_transactions
GROUP BY Product_Category
ORDER BY Avg_Order_Value DESC
LIMIT 1;

-- Find the cities that have more than 100 orders.
SELECT Shipping_City,COUNT(Order_ID) AS "Orders"
FROM ecommerce_transactions
GROUP BY Shipping_City
HAVING COUNT(Order_ID)>100;

-- Find the countries whose total revenue is greater than $10,000.
SELECT Country,SUM(Total_Amount) AS "Total_Revenue"
FROM ecommerce_transactions
GROUP BY Country
HAVING Total_Revenue>10000;

select * from ecommerce_transactions;

-- Find the total revenue for each month.
SELECT MONTHNAME(Order_Date) 'Month',MONTH(Order_Date) 'Month_Num',YEAR(Order_Date)'Year', SUM(Total_Amount) 'Revenue'
FROM ecommerce_transactions
GROUP BY YEAR(Order_Date), MONTHNAME(Order_Date),MONTH(Order_Date) 
ORDER BY YEAR(Order_Date),MONTH(Order_Date);


-- Find the number of orders for each month
SELECT MONTHNAME(Order_Date) 'Month', MONTH(Order_Date) 'Month_Num',YEAR(Order_Date) 'Year', COUNT(Order_ID) 'Orders'
FROM ecommerce_transactions
GROUP BY YEAR(Order_Date), MONTHNAME(Order_Date),MONTH(Order_Date) 
ORDER BY YEAR(Order_Date),MONTH(Order_Date);

-- Find the month with the highest revenue.
SELECT MONTHNAME(Order_Date) 'Month',YEAR(Order_Date)'Year', SUM(Total_Amount) 'Highest_Revenue'
FROM ecommerce_transactions
GROUP BY MONTHNAME(Order_Date),YEAR(Order_Date)
ORDER BY Highest_Revenue DESC
LIMIT 1;

-- Find the total revenue for each year.
SELECT YEAR(Order_Date) AS 'Year',SUM(Total_Amount) AS 'Revenue'
FROM ecommerce_transactions
GROUP BY Year;

-- Find the monthly revenue and compare it with the previous month's revenue.
SELECT *
FROM (
    SELECT 
        MONTHNAME(Order_Date) AS Month,
        MONTH(Order_Date) AS Month_num,
        SUM(Total_Amount) AS Revenue,
        YEAR(Order_Date) AS Year,
        LAG(SUM(Total_Amount)) OVER (
            ORDER BY YEAR(Order_Date), MONTH(Order_Date)
        ) AS Previous_Month_Revenue
    FROM ecommerce_transactions
    GROUP BY 
        YEAR(Order_Date),
        MONTH(Order_Date),
        MONTHNAME(Order_Date)
) AS T;

SELECT * FROM ecommerce_transactions;
-- Business: Management wants to identify their highest-value customers.

SELECT 
	Customer_ID,
    SUM(Total_Amount) AS 'Total_Amount',
    COUNT(Order_ID) AS 'Total_Orders',
    DENSE_RANK() OVER(ORDER BY SUM(Total_Amount) DESC ,COUNT(Order_ID) DESC) 'Customer_Rank'
FROM ecommerce_transactions
GROUP BY Customer_ID
ORDER BY Customer_Rank;

-- Top 3 Customers in Each Country
SELECT * FROM (
SELECT 
	Country,
    Customer_ID,
    SUM(Total_Amount) AS 'Total_Amount',
    COUNT(Order_ID) AS 'Total_Orders',
    DENSE_RANK() OVER(PARTITION BY Country ORDER BY SUM(Total_Amount) DESC, COUNT(Order_ID) DESC) AS 'Customer_Rank'
FROM ecommerce_transactions
GROUP BY Country,Customer_ID) AS t
WHERE Customer_Rank<4;

-- The company wants to compare the performance of product categories.
SELECT 
	Product_Category,
    COUNT(Order_ID) AS 'Orders',
    RANK() OVER(ORDER BY COUNT(Order_ID) DESC) 'Rank'
FROM ecommerce_transactions
GROUP BY Product_Category;

-- Business: The finance team wants to monitor month-over-month performance.

SELECT
	YEAR(Order_Date) 'Year',
	MONTHNAME(Order_Date)'MonthName',
    MONTH(Order_Date)'MonthNumber',
    SUM(Total_Amount) 'MonthRevenue',
    
    LAG(SUM(Total_Amount)) OVER(ORDER BY YEAR(Order_Date),MONTH(Order_Date),MONTHNAME(Order_Date))'Previous_Month_Total',
    
    (SUM(Total_Amount) - LAG(SUM(Total_Amount)) OVER(ORDER BY YEAR(Order_Date), MONTH(Order_Date),MONTHNAME(Order_Date))) AS 'Difference',
    
    CONCAT(ROUND(
        (
            (SUM(Total_Amount) - LAG(SUM(Total_Amount)) OVER (ORDER BY YEAR(Order_Date), MONTH(Order_Date)))
            / LAG(SUM(Total_Amount)) OVER (ORDER BY YEAR(Order_Date), MONTH(Order_Date))
        ) * 100.0, 
        2),'%'
    ) AS MoM_Percentage_Change
FROM ecommerce_transactions
GROUP BY YEAR(Order_Date),MONTH(Order_Date),MONTHNAME(Order_Date);

-- Management wants to see how revenue accumulates throughout each year.
SELECT 
	YEAR(Order_Date) 'Year',
    MONTH(Order_Date) 'Month_Num',
    MONTHNAME(Order_Date) 'Month',
    SUM(Total_Amount),
    SUM(SUM(Total_Amount)) OVER(PARTITION BY YEAR(Order_Date) ORDER BY MONTH(Order_Date)) 'YTD_Cumulative_Revenue'
FROM ecommerce_transactions
GROUP BY YEAR(Order_Date),MONTH(Order_Date), MONTHNAME(Order_Date)
ORDER BY YEAR(Order_Date),MONTH(Order_Date)
